{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Endpoint Hits",
   "type": "timeseries",
   "description": "This graph shows the total number of endpoint hits for our API.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "get_exchange_rate_requests_total",
     "legendFormat": "/convert"
    },
    {
     "expr": "get_forex_over_time_requests_total",
     "legendFormat": "/rates/historical"
    },
    {
     "expr": "list_exchange_rate_requests_total",
     "legendFormat": "/rates/latest"
    }
   ]
  },
  {
   "title": "Exchange Rate API",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "exchange_rate_api_calls", "legendFormat": "Exchange Rate API calls" },
    {
     "expr": "fallback_exchange_rate_api_calls",
     "legendFormat": "Fallback Exchange Rate API calls"
    }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "piechart",
   "description": "This graph shows cache hits.",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cache_hits_total", "legendFormat": "Cache Hits" },
    { "expr": "cache_misses_total", "legendFormat": "Cache Misses" }
   ]
  },
  {
   "title": "Average response time",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(get_exchange_rate_request_duration_seconds_sum{job=\"go_app\"}[5m]) / rate(get_exchange_rate_request_duration_seconds_count{job=\"go_app\"}[5m]) * 1000",
     "legendFormat": "/convert"
    },
    {
     "expr": "rate(get_forex_over_time_request_duration_seconds_sum{job=\"go_app\"}[5m]) / rate(get_forex_over_time_request_duration_seconds_count{job=\"go_app\"}[5m]) * 1000",
     "legendFormat": "/rates/historical"
    },
    {
     "expr": "rate(list_exchange_rate_request_duration_seconds_sum{job=\"go_app\"}[5m]) / rate(list_exchange_rate_request_duration_seconds_count{job=\"go_app\"}[5m]) * 1000",
     "legendFormat": "/rates/latest"
    }
   ]
  },
  {
   "title": "Polling Service",
   "type": "piechart",
   "description": "This panel tells about how many polls passed and how many failed.",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "api_poll_count_total", "legendFormat": "Successful Polls" },
    { "expr": "api_poll_fail_count_total", "legendFormat": "Failed Polls" }
   ]
  },
  {
   "title": "Last Polled ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "api_last_poll_timestamp_seconds * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}